service: aws-java-starter

provider:
  cors:
    origin: '*'
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
    allowCredentials: false
  name: aws
  runtime: java11
  region: us-east-1
  environment:
    TABLE_NAME: ${self:service}-${opt:stage, self:provider.stage}
    STUDENTS_TABLE: ${self:service}-students-${sls:stage}
    COURSES_TABLE: ${self:service}-courses-${sls:stage}
    GRADES_TABLE: ${self:service}-grades-${sls:stage}
    USER_POOL_ID: !Ref UserPool
    REGISTRATIONS_TABLE: ${self:service}-registrations-${sls:stage}
    TEACHERS_TABLE: ${self:service}-teachers-${sls:stage}
    NOTIFICATIONS_TABLE: ${self:service}-notifications-${sls:stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminDeleteUser
            - cognito-idp:ListUsers
          Resource: 
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.STUDENTS_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.COURSES_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.COURSES_TABLE}/index/*
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.GRADES_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.GRADES_TABLE}/index/*
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TEACHERS_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.NOTIFICATIONS_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.NOTIFICATIONS_TABLE}/index/*
            - !GetAtt UserPool.Arn
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:Query
          Resource: 
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.REGISTRATIONS_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.REGISTRATIONS_TABLE}/index/*
        - Effect: Allow
          Action:
            - cognito-idp:AdminUpdateUserAttributes
            - cognito-idp:AdminGetUser
            - cognito-idp:ListUsers
            - cognito-idp:AdminDeleteUser
          Resource: 
            - !GetAtt UserPool.Arn

package:
  artifact: target/aws-java-starter-1.0-SNAPSHOT.jar

functions:
  createItem:
    handler: com.example.handlers.CreateItemHandler
    events:
      - http:
          path: /items
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            methods:
              - POST
              - GET
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: false
  getItem:
    handler: com.example.handlers.GetItemHandler
    events:
      - http:
          path: /items/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: false
  updateItem:
    handler: com.example.handlers.UpdateItemHandler
    events:
      - http:
          path: /items/{id}
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: false
  deleteItem:
    handler: com.example.handlers.DeleteItemHandler
    events:
      - http:
          path: /items/{id}
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: false
  listItems:
    handler: com.example.handlers.ListItemsHandler
    events:
      - http:
          path: /items
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: false
  options:
    handler: com.example.handlers.OptionsHandler
    events:
      - http:
          path: /{proxy+}
          method: options
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowCredentials: false
  createStudent:
    handler: com.example.handlers.student.CreateStudentHandler
    environment:
      USER_POOL_ID: !Ref UserPool
    events:
      - http:
          path: /students
          method: post
          cors: true
  getStudent:
    handler: com.example.handlers.student.GetStudentHandler
    events:
      - http:
          path: /students/{id}
          method: get
          cors: true
  listStudents:
    handler: com.example.handlers.student.ListStudentsHandler
    events:
      - http:
          path: /students
          method: get
          cors: true
  createCourse:
    handler: com.example.handlers.course.CreateCourseHandler
    events:
      - http:
          path: /courses
          method: post
          cors: true
  getCourse:
    handler: com.example.handlers.course.GetCourseHandler
    events:
      - http:
          path: /courses/{id}
          method: get
          cors: true
  listCourses:
    handler: com.example.handlers.course.ListCoursesHandler
    events:
      - http:
          path: /courses
          method: get
          cors: true
  createGrade:
    handler: com.example.handlers.grade.CreateGradeHandler
    events:
      - http:
          path: /grades
          method: post
          cors: true
  getStudentGrades:
    handler: com.example.handlers.grade.GetStudentGradesHandler
    events:
      - http:
          path: /grades/by-student/{studentId}
          method: get
          cors: true
  getCourseGrades:
    handler: com.example.handlers.grade.GetCourseGradesHandler
    events:
      - http:
          path: /grades/by-course/{courseId}
          method: get
          cors: true
  createRegistration:
    handler: com.example.handlers.registration.CreateRegistrationHandler
    events:
      - http:
          path: /registrations
          method: post
          cors: true
  updateRegistration:
    handler: com.example.handlers.registration.UpdateRegistrationHandler
    events:
      - http:
          path: /registrations/{id}
          method: put
          cors: true
  createTeacher:
    handler: com.example.handlers.teacher.CreateTeacherHandler
    environment:
      USER_POOL_ID: !Ref UserPool
    events:
      - http:
          path: /teachers
          method: post
          cors: true
  getTeacher:
    handler: com.example.handlers.teacher.GetTeacherHandler
    events:
      - http:
          path: /teachers/{id}
          method: get
          cors: true
  listTeachers:
    handler: com.example.handlers.teacher.ListTeachersHandler
    events:
      - http:
          path: /teachers
          method: get
          cors: true
  getTeacherCourses:
    handler: com.example.handlers.teacher.GetTeacherCoursesHandler
    events:
      - http:
          path: /teachers/{id}/courses
          method: get
          cors: true
  getPendingRegistrations:
    handler: com.example.handlers.teacher.GetPendingRegistrationsHandler
    events:
      - http:
          path: /teachers/{id}/pending-registrations
          method: get
          cors: true
  getStudentRegistrations:
    handler: com.example.handlers.student.GetStudentRegistrationsHandler
    events:
      - http:
          path: /registrations/by-student/{studentId}
          method: get
          cors: true
  getStudentNotifications:
    handler: com.example.handlers.student.GetStudentNotificationsHandler
    events:
      - http:
          path: /notifications/by-student/{studentId}
          method: get
          cors: true
  listUsers:
    handler: com.example.handlers.ListUsersHandler
    events:
      - http:
          path: /users
          method: get
          cors: true
  updateUser:
    handler: com.example.handlers.user.UpdateUserHandler::handleRequest
    events:
      - http:
          path: /users/{id}
          method: put
          cors: true
  updateCourse:
    handler: com.example.handlers.course.UpdateCourseHandler::handleRequest
    events:
      - http:
          path: /courses/{id}
          method: put
          cors: true
  updateTeacher:
    handler: com.example.handlers.teacher.UpdateTeacherHandler::handleRequest
    events:
      - http:
          path: /teachers/{id}
          method: put
          cors: true
  deleteUser:
    handler: com.example.handlers.user.DeleteUserHandler
    events:
      - http:
          path: /users/{id}
          method: delete
          cors: true
  createUser:
    handler: com.example.handlers.user.CreateUserHandler
    events:
      - http:
          path: /users
          method: post
          cors: true

resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi' 
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-user-pool-${sls:stage}
        AutoVerifiedAttributes:
          - email
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: name
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: role
            AttributeDataType: String
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "1"
              MaxLength: "256"
          - Name: studentId
            AttributeDataType: String
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "1"
              MaxLength: "256"
        
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref UserPool
        ClientName: ${self:service}-client-${sls:stage}
        GenerateSecret: false
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
    StudentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.STUDENTS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    CoursesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.COURSES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: instructor
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: InstructorIndex
            KeySchema:
              - AttributeName: instructor
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    GradesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.GRADES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: studentId
            AttributeType: S
          - AttributeName: courseId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StudentIdIndex
            KeySchema:
              - AttributeName: studentId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: CourseIdIndex
            KeySchema:
              - AttributeName: courseId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

    RegistrationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REGISTRATIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: studentId
            AttributeType: S
          - AttributeName: courseId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StudentIdIndex
            KeySchema:
              - AttributeName: studentId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: CourseIdIndex
            KeySchema:
              - AttributeName: courseId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    NotificationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.NOTIFICATIONS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: studentId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: StudentIdIndex
            KeySchema:
              - AttributeName: studentId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    TeachersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TEACHERS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST